export interface BookInfo {
  bookName: string;
  publisher: string;
  chapters: string[];
}

export const ENGLISH_BOOKS: Record<string, BookInfo[]> = {
  "Grade 1": [
    {
      bookName: "Marigold (Book 1)",
      publisher: "NCERT",
      chapters: [
        "A Happy Child (Poem)",
        "Three Little Pigs",
        "After a Bath (Poem)",
        "The Bubble, the Straw, and the Shoe",
        "One Little Kitten (Poem)",
        "Lalu and Peelu",
        "Once I Saw a Little Bird (Poem)",
        "Mittu and the Yellow Mango",
        "Merry-Go-Round (Poem)",
        "Circle",
        "If I Were an Apple (Poem)",
        "Our Tree",
        "A Kite (Poem)",
        "Sundari",
        "A Little Turtle (Poem)",
        "The Tiger and the Mosquito",
        "Clouds (Poem)",
        "Anandi's Rainbow",
        "Flying Man (Poem)",
        "The Tailor and His Friend",
      ],
    },
  ],
  "Grade 2": [
    {
      bookName: "Marigold (Book 2)",
      publisher: "NCERT",
      chapters: [
        "First Day at School (Poem)",
        "Haldi's Adventure",
        "I am Lucky! (Poem)",
        "I Want",
        "A Smile (Poem)",
        "The Wind and the Sun",
        "Rain (Poem)",
        "Storm in the Garden",
        "Zoo Manners (Poem)",
        "Funny Bunny",
        "Mr. Nobody (Poem)",
        "Curlylocks and the Three Bears",
        "On My Blackboard I Can Draw (Poem)",
        "Make it Shorter",
        "I am the Music Man (Poem)",
        "The Mumbai Musicians",
        "Granny Granny Please Comb My Hair (Poem)",
        "The Magic Porridge Pot",
        "Strange Talk (Poem)",
        "The Grasshopper and the Ant",
      ],
    },
  ],
  "Grade 3": [
    {
      bookName: "Marigold (Book 3)",
      publisher: "NCERT",
      chapters: [
        "Good Morning (Poem)",
        "The Magic Garden",
        "Bird Talk (Poem)",
        "Nina and the Baby Sparrows",
        "Little by Little (Poem)",
        "The Enormous Turnip",
        "Sea Song (Poem)",
        "A Little Fish Story",
        "The Balloon Man (Poem)",
        "The Yellow Butterfly",
        "Trains (Poem)",
        "The Story of the Road",
        "Puppy and I (Poem)",
        "Little Tiger, Big Tiger",
        "What's in the Mailbox? (Poem)",
        "My Silly Sister",
        "Don't Tell (Poem)",
        "He is My Brother",
        "How Creatures Move (Poem)",
        "The Ship of the Desert",
      ],
    },
  ],
  "Grade 4": [
    {
      bookName: "Marigold (Book 4)",
      publisher: "NCERT",
      chapters: [
        "Wake Up! (Poem)",
        "Neha's Alarm Clock",
        "Noses (Poem)",
        "The Little Fir Tree",
        "Run! (Poem)",
        "Nasruddin's Aim",
        "Why? (Poem)",
        "Alice in Wonderland",
        "Don't be Afraid of the Dark (Poem)",
        "Helen Keller",
        "Hiawatha (Poem)",
        "The Scholar's Mother Tongue",
        "A Watering Rhyme (Poem)",
        "The Giving Tree",
        "Books (Poem)",
        "Going to Buy a Book",
        "The Naughty Boy (Poem)",
        "Pinocchio",
      ],
    },
  ],
  "Grade 5": [
    {
      bookName: "Marigold (Book 5)",
      publisher: "NCERT",
      chapters: [
        "Ice-cream Man (Poem)",
        "Wonderful Waste!",
        "Teamwork (Poem)",
        "Flying Together",
        "My Shadow (Poem)",
        "Robinson Crusoe Discovers a Footprint",
        "Crying (Poem)",
        "My Elder Brother",
        "The Lazy Frog (Poem)",
        "Rip Van Winkle",
        "Class Discussion (Poem)",
        "The Talkative Barber",
        "Topsy-turvy Land (Poem)",
        "Gulliver's Travels",
        "Nobody's Friend (Poem)",
        "Around the World",
        "Sing a Song of People (Poem)",
        "Malu Bhalu",
        "Who Will be Ningthou?",
      ],
    },
  ],
  "Grade 6": [
    {
      bookName: "Honeysuckle",
      publisher: "NCERT",
      chapters: [
        "Who Did Patrick's Homework?",
        "How the Dog Found Himself a New Master!",
        "Taro's Reward",
        "An Indian American Woman in Space: Kalpana Chawla",
        "A Different Kind of School",
        "Who I Am",
        "Fair Play",
        "A Game of Chance",
        "Desert Animals",
        "The Banyan Tree",
        "A House, A Home (Poem)",
        "The Kite (Poem)",
        "The Quarrel (Poem)",
        "Beauty (Poem)",
        "Where Do All the Teachers Go? (Poem)",
        "The Wonderful Words (Poem)",
        "Vocation (Poem)",
        "What If (Poem)",
      ],
    },
    {
      bookName: "A Pact with the Sun",
      publisher: "NCERT (Supplementary)",
      chapters: [
        "A Tale of Two Birds",
        "The Friendly Mongoose",
        "The Shepherd's Treasure",
        "The Old-Clock Shop",
        "Tansen",
        "The Monkey and the Crocodile",
        "The Wonder Called Sleep",
        "A Pact with the Sun",
        "What Happened to the Reptiles",
        "A Strange Wrestling Match",
      ],
    },
  ],
  "Grade 7": [
    {
      bookName: "Honeycomb",
      publisher: "NCERT",
      chapters: [
        "Three Questions",
        "A Gift of Chappals",
        "Gopal and the Hilsa Fish",
        "The Ashes That Made Trees Bloom",
        "Quality",
        "Expert Detectives",
        "The Invention of Vita-Wonk",
        "A Homage to Our Brave Soldiers",
        "The Squirrel (Poem)",
        "The Rebel (Poem)",
        "The Shed (Poem)",
        "Chivvy (Poem)",
        "Trees (Poem)",
        "Mystery of the Talking Fan (Poem)",
        "Dad and the Cat and the Tree (Poem)",
        "Garden Snake (Poem)",
        "Meadow Surprises (Poem)",
      ],
    },
    {
      bookName: "An Alien Hand",
      publisher: "NCERT (Supplementary)",
      chapters: [
        "The Tiny Teacher",
        "Bringing Up Kari",
        "The Desert",
        "The Cop and the Anthem",
        "Golu Grows a Nose",
        "I Want Something in a Cage",
        "Chandni",
        "The Bear Story",
        "A Tiger in the House",
        "An Alien Hand",
      ],
    },
  ],
  "Grade 8": [
    {
      bookName: "Honeydew",
      publisher: "NCERT",
      chapters: [
        "The Best Christmas Present in the World",
        "The Tsunami",
        "Glimpses of the Past",
        "Bepin Choudhury's Lapse of Memory",
        "The Summit Within",
        "This is Jody's Fawn",
        "A Visit to Cambridge",
        "A Short Monsoon Diary",
        "The Great Stone Face – I",
        "The Great Stone Face – II",
        "The Ant and the Cricket (Poem)",
        "Geography Lesson (Poem)",
        "Macavity: The Mystery Cat (Poem)",
        "The Last Bargain (Poem)",
        "The School Boy (Poem)",
        "The Duck and the Kangaroo (Poem)",
        "When I Set Out For Lyonnesse (Poem)",
        "On the Grasshopper and Cricket (Poem)",
      ],
    },
    {
      bookName: "It So Happened",
      publisher: "NCERT (Supplementary)",
      chapters: [
        "How the Camel Got His Hump",
        "Children at Work",
        "The Selfish Giant",
        "The Treasure Within",
        "Princess September",
        "The Fight",
        "Jalebis",
        "Ancient Education System of India",
        "The Comet – I",
        "The Comet – II",
      ],
    },
  ],
  "Grade 9": [
    {
      bookName: "Beehive",
      publisher: "NCERT",
      chapters: [
        "The Fun They Had",
        "The Sound of Music",
        "The Little Girl",
        "A Truly Beautiful Mind",
        "The Snake and the Mirror",
        "My Childhood",
        "Reach for the Top",
        "Kathmandu",
        "If I Were You",
        "The Road Not Taken (Poem)",
        "Wind (Poem)",
        "Rain on the Roof (Poem)",
        "The Lake Isle of Innisfree (Poem)",
        "A Legend of the Northland (Poem)",
        "No Men Are Foreign (Poem)",
        "On Killing a Tree (Poem)",
        "A Slumber Did My Spirit Seal (Poem)",
      ],
    },
    {
      bookName: "Moments",
      publisher: "NCERT (Supplementary)",
      chapters: [
        "The Lost Child",
        "The Adventures of Toto",
        "Iswaran the Storyteller",
        "In the Kingdom of Fools",
        "The Happy Prince",
        "Weathering the Storm in Ersama",
        "The Last Leaf",
        "A House Is Not a Home",
        "The Accidental Tourist",
        "The Beggar",
      ],
    },
  ],
  "Grade 10": [
    {
      bookName: "First Flight",
      publisher: "NCERT",
      chapters: [
        "A Letter to God",
        "Nelson Mandela: Long Walk to Freedom",
        "Two Stories About Flying",
        "From the Diary of Anne Frank",
        "Glimpses of India",
        "Mijbil the Otter",
        "Madam Rides the Bus",
        "The Sermon at Benares",
        "The Proposal",
        "Dust of Snow (Poem)",
        "Fire and Ice (Poem)",
        "A Tiger in the Zoo (Poem)",
        "How to Tell Wild Animals (Poem)",
        "The Ball Poem (Poem)",
        "Amanda! (Poem)",
        "The Trees (Poem)",
        "Fog (Poem)",
        "The Tale of Custard the Dragon (Poem)",
        "For Anne Gregory (Poem)",
      ],
    },
    {
      bookName: "Footprints without Feet",
      publisher: "NCERT (Supplementary)",
      chapters: [
        "A Triumph of Surgery",
        "The Thief's Story",
        "The Midnight Visitor",
        "A Question of Trust",
        "Footprints without Feet",
        "The Making of a Scientist",
        "The Necklace",
        "The Hack Driver",
        "Bholi",
        "The Book That Saved the Earth",
      ],
    },
  ],
};

export function getEnglishBooks(className: string): BookInfo[] {
  return ENGLISH_BOOKS[className] || [];
}

export function getChaptersForBook(className: string, bookName: string): string[] {
  const books = ENGLISH_BOOKS[className] || [];
  const book = books.find(b => b.bookName === bookName);
  return book ? book.chapters : [];
}

export function getAllChaptersForGrade(className: string): { bookName: string; chapter: string }[] {
  const books = ENGLISH_BOOKS[className] || [];
  const result: { bookName: string; chapter: string }[] = [];
  for (const book of books) {
    for (const chapter of book.chapters) {
      result.push({ bookName: book.bookName, chapter });
    }
  }
  return result;
}
