export interface BookInfo {
  bookName: string;
  publisher: string;
  chapters: string[];
}

export const NCERT_CHAPTER_DATA: Record<string, Record<string, BookInfo[]>> = {
  "Grade 1": {
    "Mathematics": [
      {
        bookName: "Math-Magic (Book 1)",
        publisher: "NCERT",
        chapters: [
          "Shapes and Space",
          "Numbers from One to Nine",
          "Addition",
          "Subtraction",
          "Numbers from Ten to Twenty",
          "Time",
          "Measurement",
          "Numbers from Twenty-one to Fifty",
          "Data Handling",
          "Patterns",
          "Numbers",
          "Money",
          "How Many",
        ],
      },
    ],
    "English": [
      {
        bookName: "Marigold (Book 1)",
        publisher: "NCERT",
        chapters: [
          "A Happy Child (Poem)",
          "Three Little Pigs",
          "After a Bath (Poem)",
          "The Bubble, the Straw, and the Shoe",
          "One Little Kitten (Poem)",
          "Lalu and Peelu",
          "Once I Saw a Little Bird (Poem)",
          "Mittu and the Yellow Mango",
          "Merry-Go-Round (Poem)",
          "Circle",
          "If I Were an Apple (Poem)",
          "Our Tree",
          "A Kite (Poem)",
          "Sundari",
          "A Little Turtle (Poem)",
          "The Tiger and the Mosquito",
          "Clouds (Poem)",
          "Anandi's Rainbow",
          "Flying Man (Poem)",
          "The Tailor and His Friend",
        ],
      },
    ],
    "Hindi": [
      {
        bookName: "Rimjhim (Part 1)",
        publisher: "NCERT",
        chapters: [
          "झूला",
          "आम की कहानी",
          "आम की टोकरी (कविता)",
          "पत्ते ही पत्ते",
          "पकौड़ी (कविता)",
          "छुक-छुक गाड़ी",
          "रसोईघर",
          "चूहो! म्याऊँ सो रही है (कविता)",
          "बंदर और गिलहरी (कविता)",
          "पगड़ी",
          "पतंग (कविता)",
          "गेंद-बल्ला",
          "बंदर गया खेत में भाग (कविता)",
          "एक बुढ़िया",
          "मैं भी... (कविता)",
          "लालू और पीलू",
          "चकई के चकदुम (कविता)",
          "छोटी का कमाल",
          "चार चने",
          "भगदड़ (कविता)",
          "हलीम चला चाँद पर",
          "हाथी चल्लम चल्लम (कविता)",
          "सात पूँछ का चूहा",
        ],
      },
    ],
    "EVS": [
      {
        bookName: "Looking Around (Part 1)",
        publisher: "NCERT",
        chapters: [
          "My Family",
          "My Body",
          "My Home",
          "My School",
          "Food We Eat",
          "Clothes We Wear",
          "Animals Around Us",
          "Plants Around Us",
          "Water",
          "Air",
          "Seasons",
          "Festivals",
        ],
      },
    ],
  },
  "Grade 2": {
    "Mathematics": [
      {
        bookName: "Math-Magic (Book 2)",
        publisher: "NCERT",
        chapters: [
          "What is Long, What is Round?",
          "Counting in Groups",
          "How Much Can You Carry?",
          "Counting in Tens",
          "Patterns",
          "Footprints",
          "Jugs and Mugs",
          "Tens and Ones",
          "My Funday",
          "Add Our Points",
          "Lines and Lines",
          "Give and Take",
          "The Longest Step",
          "Birds Come, Birds Go",
          "How Many Ponytails?",
        ],
      },
    ],
    "English": [
      {
        bookName: "Marigold (Book 2)",
        publisher: "NCERT",
        chapters: [
          "First Day at School (Poem)",
          "Haldi's Adventure",
          "I am Lucky! (Poem)",
          "I Want",
          "A Smile (Poem)",
          "The Wind and the Sun",
          "Rain (Poem)",
          "Storm in the Garden",
          "Zoo Manners (Poem)",
          "Funny Bunny",
          "Mr. Nobody (Poem)",
          "Curlylocks and the Three Bears",
          "On My Blackboard I Can Draw (Poem)",
          "Make it Shorter",
          "I am the Music Man (Poem)",
          "The Mumbai Musicians",
          "Granny Granny Please Comb My Hair (Poem)",
          "The Magic Porridge Pot",
          "Strange Talk (Poem)",
          "The Grasshopper and the Ant",
        ],
      },
    ],
    "Hindi": [
      {
        bookName: "Rimjhim (Part 2)",
        publisher: "NCERT",
        chapters: [
          "ऊँट चला (कविता)",
          "भालू ने खेली फुटबॉल",
          "म्याऊँ, म्याऊँ!! (कविता)",
          "अधिक बलवान कौन?",
          "दोस्त की मदद (कविता)",
          "बहुत हुआ",
          "मेरी किताब (कविता)",
          "तितली और कली",
          "बुलबुल (कविता)",
          "मीठी सारंगी",
          "टेसू राजा बीच बाज़ार (कविता)",
          "बस के नीचे बाघ",
          "सूरज जल्दी आना जी (कविता)",
          "शेखीबाज़ मक्खी",
          "बोलती पोटली (कविता)",
          "चार दोस्त",
        ],
      },
    ],
    "EVS": [
      {
        bookName: "Looking Around (Part 2)",
        publisher: "NCERT",
        chapters: [
          "My Family and I",
          "My Neighbourhood",
          "Keeping Clean",
          "Good Habits",
          "Safety Rules",
          "Our Helpers",
          "Means of Transport",
          "Means of Communication",
          "Our National Symbols",
          "Plants",
          "Animals",
          "Weather and Seasons",
        ],
      },
    ],
  },
  "Grade 3": {
    "Mathematics": [
      {
        bookName: "Math-Magic (Book 3)",
        publisher: "NCERT",
        chapters: [
          "Where to Look From",
          "Fun with Numbers",
          "Give and Take",
          "Long and Short",
          "Shapes and Designs",
          "Fun with Give and Take",
          "Time Goes On",
          "Who is Heavier?",
          "How Many Times?",
          "Play with Patterns",
          "Jugs and Mugs",
          "Can We Share?",
          "Smart Charts!",
          "Rupees and Paise",
        ],
      },
    ],
    "English": [
      {
        bookName: "Marigold (Book 3)",
        publisher: "NCERT",
        chapters: [
          "Good Morning (Poem)",
          "The Magic Garden",
          "Bird Talk (Poem)",
          "Nina and the Baby Sparrows",
          "Little by Little (Poem)",
          "The Enormous Turnip",
          "Sea Song (Poem)",
          "A Little Fish Story",
          "The Balloon Man (Poem)",
          "The Yellow Butterfly",
          "Trains (Poem)",
          "The Story of the Road",
          "Puppy and I (Poem)",
          "Little Tiger, Big Tiger",
          "What's in the Mailbox? (Poem)",
          "My Silly Sister",
          "Don't Tell (Poem)",
          "He is My Brother",
          "How Creatures Move (Poem)",
          "The Ship of the Desert",
        ],
      },
    ],
    "Hindi": [
      {
        bookName: "Rimjhim (Part 3)",
        publisher: "NCERT",
        chapters: [
          "कक्कू",
          "शेखीबाज़ मक्खी (कविता)",
          "चाँद वाली अम्मा",
          "मन करता है (कविता)",
          "बहादुर बित्तो",
          "हमसे सब कहते (कविता)",
          "टिपटिपवा",
          "बंदर बाँट",
          "अक्ल बड़ी या भैंस",
          "क्योंजीमल और कैसे कैसलिया (कविता)",
          "मीरा बहन और बाघ",
          "जब मुझे साँप ने काटा (कविता)",
          "मिर्च का मज़ा",
          "सबसे अच्छा पेड़ (कविता)",
        ],
      },
    ],
    "EVS": [
      {
        bookName: "Looking Around (Part 3)",
        publisher: "NCERT",
        chapters: [
          "Poonam's Day Out",
          "The Plant Fairy",
          "Water O' Water!",
          "Our First School",
          "Chhotu's House",
          "Foods We Eat",
          "Saying without Speaking",
          "Flying High",
          "It's Raining",
          "What is Cooking?",
          "From Here to There",
          "Work We Do",
          "Sharing Our Feelings",
          "The Story of Food",
          "Making Pots",
          "Games We Play",
          "Here Comes a Letter",
          "A House Like This",
          "Our Friends – Animals",
          "Drop by Drop",
          "Families can be Different",
          "Left-Right",
          "A Beautiful Cloth!",
          "Web of Life",
        ],
      },
    ],
  },
  "Grade 4": {
    "Mathematics": [
      {
        bookName: "Math-Magic (Book 4)",
        publisher: "NCERT",
        chapters: [
          "Building with Bricks",
          "Long and Short",
          "A Trip to Bhopal",
          "Tick-Tick-Tick",
          "The Way the World Looks",
          "The Junk Seller",
          "Jugs and Mugs",
          "Carts and Wheels",
          "Halves and Quarters",
          "Play with Patterns",
          "Tables and Shares",
          "How Heavy? How Light?",
          "Fields and Fences",
          "Smart Charts!",
        ],
      },
    ],
    "English": [
      {
        bookName: "Marigold (Book 4)",
        publisher: "NCERT",
        chapters: [
          "Wake Up! (Poem)",
          "Neha's Alarm Clock",
          "Noses (Poem)",
          "The Little Fir Tree",
          "Run! (Poem)",
          "Nasruddin's Aim",
          "Why? (Poem)",
          "Alice in Wonderland",
          "Don't be Afraid of the Dark (Poem)",
          "Helen Keller",
          "Hiawatha (Poem)",
          "The Scholar's Mother Tongue",
          "A Watering Rhyme (Poem)",
          "The Giving Tree",
          "Books (Poem)",
          "Going to Buy a Book",
          "The Naughty Boy (Poem)",
          "Pinocchio",
        ],
      },
    ],
    "Hindi": [
      {
        bookName: "Rimjhim (Part 4)",
        publisher: "NCERT",
        chapters: [
          "मन के भोले-भाले बादल (कविता)",
          "जैसा सवाल वैसा जवाब",
          "किरमिच की गेंद (कविता)",
          "पापा जब बच्चे थे",
          "दोस्त की पोशाक (कविता)",
          "नाव बनाओ नाव बनाओ",
          "दान का हिसाब",
          "कौन? (कविता)",
          "स्वतंत्रता की ओर",
          "थप्प रोटी थप्प दाल (कविता)",
          "पढ़क्कू की सूझ",
          "सुनीता की पहिया कुर्सी",
          "हुदहुद (कविता)",
          "मुफ़्त ही मुफ़्त",
        ],
      },
    ],
    "EVS": [
      {
        bookName: "Looking Around (Part 4)",
        publisher: "NCERT",
        chapters: [
          "Going to School",
          "Ear to Ear",
          "A Day with Nandu",
          "The Story of Amrita",
          "Anita and the Honeybees",
          "Omana's Journey",
          "From the Window",
          "Reaching Grandmother's House",
          "Changing Families",
          "Hu Tu Tu, Hu Tu Tu",
          "The Valley of Flowers",
          "Changing Times",
          "A River's Tale",
          "Basva's Farm",
          "From Market to Home",
          "A Busy Month",
          "Nandita in Mumbai",
          "Too Much Water, Too Little Water",
          "Abdul in the Garden",
          "Eating Together",
          "Food and Fun",
          "The World in My Home",
          "Pochampalli",
          "Home and Abroad",
          "Spicy Riddles",
          "Defence Officer: Wahida",
          "Chuskit Goes to School",
        ],
      },
    ],
  },
  "Grade 5": {
    "Mathematics": [
      {
        bookName: "Math-Magic (Book 5)",
        publisher: "NCERT",
        chapters: [
          "The Fish Tale",
          "Shapes and Angles",
          "How Many Squares?",
          "Parts and Wholes",
          "Does it Look the Same?",
          "Be My Multiple, I'll be Your Factor",
          "Can You See the Pattern?",
          "Mapping Your Way",
          "Boxes and Sketches",
          "Tenths and Hundredths",
          "Area and its Boundary",
          "Smart Charts!",
          "Ways to Multiply and Divide",
          "How Big? How Heavy?",
        ],
      },
    ],
    "English": [
      {
        bookName: "Marigold (Book 5)",
        publisher: "NCERT",
        chapters: [
          "Ice-cream Man (Poem)",
          "Wonderful Waste!",
          "Teamwork (Poem)",
          "Flying Together",
          "My Shadow (Poem)",
          "Robinson Crusoe Discovers a Footprint",
          "Crying (Poem)",
          "My Elder Brother",
          "The Lazy Frog (Poem)",
          "Rip Van Winkle",
          "Class Discussion (Poem)",
          "The Talkative Barber",
          "Topsy-turvy Land (Poem)",
          "Gulliver's Travels",
          "Nobody's Friend (Poem)",
          "Around the World",
          "Sing a Song of People (Poem)",
          "Malu Bhalu",
          "Who Will be Ningthou?",
        ],
      },
    ],
    "Hindi": [
      {
        bookName: "Rimjhim (Part 5)",
        publisher: "NCERT",
        chapters: [
          "राख की रस्सी (लोककथा)",
          "फ़सलों के त्योहार (कविता)",
          "खिलौनेवाला (कविता)",
          "नन्हा फ़नकार",
          "जहाँ चाह वहाँ राह",
          "चिट्ठी का सफ़र",
          "डाकिए की कहानी, कँवरसिंह की ज़ुबानी",
          "वे दिन भी क्या दिन थे!",
          "एक माँ की बेबसी (कविता)",
          "बिशन की दिलेरी",
          "अगर पेड़ भी चलते होते (कविता)",
          "जो देखकर भी नहीं देखते",
          "स्वामी की दादी",
          "बाघ आया उस रात (कविता)",
          "गुरु और चेला",
          "पानी रे पानी (कविता)",
          "छोटी-सी हमारी नदी (कविता)",
          "गुल्लक",
        ],
      },
    ],
    "EVS": [
      {
        bookName: "Looking Around (Part 5)",
        publisher: "NCERT",
        chapters: [
          "Super Senses",
          "A Snake Charmer's Story",
          "From Tasting to Digesting",
          "Mangoes Round the Year",
          "Seeds and Seeds",
          "Every Drop Counts",
          "Experiments with Water",
          "A Treat for Mosquitoes",
          "Up You Go!",
          "Walls Tell Stories",
          "Sunita in Space",
          "What if it Finishes?",
          "A Shelter So High!",
          "When the Earth Shook!",
          "Blow Hot, Blow Cold",
          "Who Will Do This Work?",
          "Across the Wall",
          "No Place for Us?",
          "A Seed Tells a Farmer's Story",
          "Whose Forests?",
          "Like Father, Like Daughter",
          "On the Move Again",
        ],
      },
    ],
  },
  "Grade 6": {
    "Mathematics": [
      {
        bookName: "Mathematics (Class VI)",
        publisher: "NCERT",
        chapters: [
          "Knowing Our Numbers",
          "Whole Numbers",
          "Playing with Numbers",
          "Basic Geometrical Ideas",
          "Understanding Elementary Shapes",
          "Integers",
          "Fractions",
          "Decimals",
          "Data Handling",
          "Mensuration",
          "Algebra",
          "Ratio and Proportion",
          "Symmetry",
          "Practical Geometry",
        ],
      },
    ],
    "Science": [
      {
        bookName: "Science (Class VI)",
        publisher: "NCERT",
        chapters: [
          "Food: Where Does it Come From?",
          "Components of Food",
          "Fibre to Fabric",
          "Sorting Materials into Groups",
          "Separation of Substances",
          "Changes Around Us",
          "Getting to Know Plants",
          "Body Movements",
          "The Living Organisms and Their Surroundings",
          "Motion and Measurement of Distances",
          "Light, Shadows and Reflections",
          "Electricity and Circuits",
          "Fun with Magnets",
          "Water",
          "Air Around Us",
          "Garbage In, Garbage Out",
        ],
      },
    ],
    "English": [
      {
        bookName: "Honeysuckle",
        publisher: "NCERT",
        chapters: [
          "Who Did Patrick's Homework?",
          "How the Dog Found Himself a New Master!",
          "Taro's Reward",
          "An Indian American Woman in Space: Kalpana Chawla",
          "A Different Kind of School",
          "Who I Am",
          "Fair Play",
          "A Game of Chance",
          "Desert Animals",
          "The Banyan Tree",
          "A House, A Home (Poem)",
          "The Kite (Poem)",
          "The Quarrel (Poem)",
          "Beauty (Poem)",
          "Where Do All the Teachers Go? (Poem)",
          "The Wonderful Words (Poem)",
          "Vocation (Poem)",
          "What If (Poem)",
        ],
      },
      {
        bookName: "A Pact with the Sun",
        publisher: "NCERT (Supplementary)",
        chapters: [
          "A Tale of Two Birds",
          "The Friendly Mongoose",
          "The Shepherd's Treasure",
          "The Old-Clock Shop",
          "Tansen",
          "The Monkey and the Crocodile",
          "The Wonder Called Sleep",
          "A Pact with the Sun",
          "What Happened to the Reptiles",
          "A Strange Wrestling Match",
        ],
      },
    ],
    "Hindi": [
      {
        bookName: "Vasant (Part 1)",
        publisher: "NCERT",
        chapters: [
          "वह चिड़िया जो (कविता)",
          "बचपन",
          "नादान दोस्त",
          "चाँद से थोड़ी सी गप्पें (कविता)",
          "अक्षरों का महत्व",
          "पार नज़र के",
          "साथी हाथ बढ़ाना (कविता)",
          "ऐसे-ऐसे",
          "टिकट अलबम",
          "झाँसी की रानी (कविता)",
          "जो देखकर भी नहीं देखते",
          "संसार पुस्तक है (कविता)",
          "मैं सबसे छोटी होऊं (कविता)",
          "लोकगीत",
          "नौकर",
          "वन के मार्ग में (कविता)",
          "साँस-साँस में बाँस",
        ],
      },
    ],
    "Social Science": [
      {
        bookName: "Our Past – I (History)",
        publisher: "NCERT",
        chapters: [
          "What, Where, How and When?",
          "From Hunting-Gathering to Growing Food",
          "In the Earliest Cities",
          "What Books and Burials Tell Us",
          "Kingdoms, Kings and an Early Republic",
          "New Questions and Ideas",
          "Ashoka, The Emperor Who Gave Up War",
          "Vital Villages, Thriving Towns",
          "Traders, Kings and Pilgrims",
          "New Empires and Kingdoms",
          "Buildings, Paintings and Books",
        ],
      },
      {
        bookName: "The Earth: Our Habitat (Geography)",
        publisher: "NCERT",
        chapters: [
          "The Earth in the Solar System",
          "Globe: Latitudes and Longitudes",
          "Motions of the Earth",
          "Maps",
          "Major Domains of the Earth",
          "Major Landforms of the Earth",
          "Our Country – India",
          "India: Climate, Vegetation and Wildlife",
        ],
      },
      {
        bookName: "Social and Political Life – I (Civics)",
        publisher: "NCERT",
        chapters: [
          "Understanding Diversity",
          "Diversity and Discrimination",
          "What is Government?",
          "Key Elements of a Democratic Government",
          "Panchayati Raj",
          "Rural Administration",
          "Urban Administration",
          "Rural Livelihoods",
          "Urban Livelihoods",
        ],
      },
    ],
    "Sanskrit": [
      {
        bookName: "Ruchira (Part 1)",
        publisher: "NCERT",
        chapters: [
          "शब्द परिचयः – I",
          "शब्द परिचयः – II",
          "शब्द परिचयः – III",
          "विद्यालयः",
          "वृक्षाः",
          "समुद्रतटः",
          "बकस्य प्रतीकारः",
          "सूक्तिस्तबकः",
          "क्रीडास्पर्धा",
          "कृषिकाः कर्मवीराः",
          "पुष्पोत्सवः",
          "दशमः त्वम् असि",
          "विमानयानं रचयाम",
          "अहह आः च",
          "मातुलचन्द्र",
        ],
      },
    ],
  },
  "Grade 7": {
    "Mathematics": [
      {
        bookName: "Mathematics (Class VII)",
        publisher: "NCERT",
        chapters: [
          "Integers",
          "Fractions and Decimals",
          "Data Handling",
          "Simple Equations",
          "Lines and Angles",
          "The Triangle and its Properties",
          "Congruence of Triangles",
          "Comparing Quantities",
          "Rational Numbers",
          "Practical Geometry",
          "Perimeter and Area",
          "Algebraic Expressions",
          "Exponents and Powers",
          "Symmetry",
          "Visualising Solid Shapes",
        ],
      },
    ],
    "Science": [
      {
        bookName: "Science (Class VII)",
        publisher: "NCERT",
        chapters: [
          "Nutrition in Plants",
          "Nutrition in Animals",
          "Fibre to Fabric",
          "Heat",
          "Acids, Bases and Salts",
          "Physical and Chemical Changes",
          "Weather, Climate and Adaptations of Animals to Climate",
          "Winds, Storms and Cyclones",
          "Soil",
          "Respiration in Organisms",
          "Transportation in Animals and Plants",
          "Reproduction in Plants",
          "Motion and Time",
          "Electric Current and its Effects",
          "Light",
          "Water: A Precious Resource",
          "Forests: Our Lifeline",
          "Wastewater Story",
        ],
      },
    ],
    "English": [
      {
        bookName: "Honeycomb",
        publisher: "NCERT",
        chapters: [
          "Three Questions",
          "A Gift of Chappals",
          "Gopal and the Hilsa Fish",
          "The Ashes That Made Trees Bloom",
          "Quality",
          "Expert Detectives",
          "The Invention of Vita-Wonk",
          "A Homage to Our Brave Soldiers",
          "The Squirrel (Poem)",
          "The Rebel (Poem)",
          "The Shed (Poem)",
          "Chivvy (Poem)",
          "Trees (Poem)",
          "Mystery of the Talking Fan (Poem)",
          "Dad and the Cat and the Tree (Poem)",
          "Garden Snake (Poem)",
          "Meadow Surprises (Poem)",
        ],
      },
      {
        bookName: "An Alien Hand",
        publisher: "NCERT (Supplementary)",
        chapters: [
          "The Tiny Teacher",
          "Bringing Up Kari",
          "The Desert",
          "The Cop and the Anthem",
          "Golu Grows a Nose",
          "I Want Something in a Cage",
          "Chandni",
          "The Bear Story",
          "A Tiger in the House",
          "An Alien Hand",
        ],
      },
    ],
    "Hindi": [
      {
        bookName: "Vasant (Part 2)",
        publisher: "NCERT",
        chapters: [
          "हम पंछी उन्मुक्त गगन के (कविता)",
          "दादी माँ",
          "हिमालय की बेटियाँ",
          "कठपुतली (कविता)",
          "मिठाईवाला",
          "रक्त और हमारा शरीर",
          "पापा खो गए",
          "शाम – एक किसान (कविता)",
          "चिड़िया की बच्ची",
          "अपूर्व अनुभव",
          "रहीम के दोहे (कविता)",
          "कंचा",
          "एक तिनका (कविता)",
          "खानपान की बदलती तसवीर",
          "नीलकंठ",
          "भोर और बरखा (कविता)",
          "वीर कुँवर सिंह",
          "संघर्ष के कारण मैं तुनुकमिज़ाज हो गया – धनराज",
        ],
      },
    ],
    "Social Science": [
      {
        bookName: "Our Past – II (History)",
        publisher: "NCERT",
        chapters: [
          "Tracing Changes Through a Thousand Years",
          "New Kings and Kingdoms",
          "The Delhi Sultans",
          "The Mughal Empire",
          "Rulers and Buildings",
          "Towns, Traders and Craftspersons",
          "Tribes, Nomads and Settled Communities",
          "Devotional Paths to the Divine",
          "The Making of Regional Cultures",
          "Eighteenth-Century Political Formations",
        ],
      },
      {
        bookName: "Our Environment (Geography)",
        publisher: "NCERT",
        chapters: [
          "Environment",
          "Inside Our Earth",
          "Our Changing Earth",
          "Air",
          "Water",
          "Natural Vegetation and Wildlife",
          "Human Environment – Settlement, Transport and Communication",
          "Human Environment Interactions – The Tropical and the Subtropical Region",
          "Life in the Temperate Grasslands",
          "Life in the Deserts",
        ],
      },
      {
        bookName: "Social and Political Life – II (Civics)",
        publisher: "NCERT",
        chapters: [
          "On Equality",
          "Role of the Government in Health",
          "How the State Government Works",
          "Growing Up as Boys and Girls",
          "Women Change the World",
          "Understanding Media",
          "Understanding Advertising",
          "Markets Around Us",
          "A Shirt in the Market",
        ],
      },
    ],
    "Sanskrit": [
      {
        bookName: "Ruchira (Part 2)",
        publisher: "NCERT",
        chapters: [
          "सुभाषितानि",
          "दुर्बुद्धिः विनश्यति",
          "स्वावलम्बनम्",
          "हास्यबालकविसम्मेलनम्",
          "पण्डिता रमाबाई",
          "सदाचारः",
          "संकल्पः सिद्धिदायकः",
          "त्रिवर्णः ध्वजः",
          "अहमपि विद्यालयं गमिष्यामि",
          "विश्वबन्धुत्वम्",
          "समवायो हि दुर्जयः",
          "विद्याधनम्",
          "अमृतं संस्कृतम्",
          "अनारिकायाः जिज्ञासा",
          "लालनगीतम्",
        ],
      },
    ],
  },
  "Grade 8": {
    "Mathematics": [
      {
        bookName: "Mathematics (Class VIII)",
        publisher: "NCERT",
        chapters: [
          "Rational Numbers",
          "Linear Equations in One Variable",
          "Understanding Quadrilaterals",
          "Practical Geometry",
          "Data Handling",
          "Squares and Square Roots",
          "Cubes and Cube Roots",
          "Comparing Quantities",
          "Algebraic Expressions and Identities",
          "Visualising Solid Shapes",
          "Mensuration",
          "Exponents and Powers",
          "Direct and Inverse Proportions",
          "Factorisation",
          "Introduction to Graphs",
          "Playing with Numbers",
        ],
      },
    ],
    "Science": [
      {
        bookName: "Science (Class VIII)",
        publisher: "NCERT",
        chapters: [
          "Crop Production and Management",
          "Microorganisms: Friend and Foe",
          "Synthetic Fibres and Plastics",
          "Materials: Metals and Non-Metals",
          "Coal and Petroleum",
          "Combustion and Flame",
          "Conservation of Plants and Animals",
          "Cell – Structure and Functions",
          "Reproduction in Animals",
          "Reaching the Age of Adolescence",
          "Force and Pressure",
          "Friction",
          "Sound",
          "Chemical Effects of Electric Current",
          "Some Natural Phenomena",
          "Light",
          "Stars and the Solar System",
          "Pollution of Air and Water",
        ],
      },
    ],
    "English": [
      {
        bookName: "Honeydew",
        publisher: "NCERT",
        chapters: [
          "The Best Christmas Present in the World",
          "The Tsunami",
          "Glimpses of the Past",
          "Bepin Choudhury's Lapse of Memory",
          "The Summit Within",
          "This is Jody's Fawn",
          "A Visit to Cambridge",
          "A Short Monsoon Diary",
          "The Great Stone Face – I",
          "The Great Stone Face – II",
          "The Ant and the Cricket (Poem)",
          "Geography Lesson (Poem)",
          "Macavity: The Mystery Cat (Poem)",
          "The Last Bargain (Poem)",
          "The School Boy (Poem)",
          "The Duck and the Kangaroo (Poem)",
          "When I Set Out For Lyonnesse (Poem)",
          "On the Grasshopper and Cricket (Poem)",
        ],
      },
      {
        bookName: "It So Happened",
        publisher: "NCERT (Supplementary)",
        chapters: [
          "How the Camel Got His Hump",
          "Children at Work",
          "The Selfish Giant",
          "The Treasure Within",
          "Princess September",
          "The Fight",
          "Jalebis",
          "Ancient Education System of India",
          "The Comet – I",
          "The Comet – II",
        ],
      },
    ],
    "Hindi": [
      {
        bookName: "Vasant (Part 3)",
        publisher: "NCERT",
        chapters: [
          "ध्वनि (कविता)",
          "लाख की चूड़ियाँ",
          "बस की यात्रा",
          "दीवानों की हस्ती (कविता)",
          "चिट्ठियों की अनूठी दुनिया",
          "भगवान के डाकिए (कविता)",
          "क्या निराश हुआ जाए",
          "यह सबसे कठिन समय नहीं (कविता)",
          "कबीर की साखियाँ",
          "कामचोर",
          "जब सिनेमा ने बोलना सीखा",
          "सुदामा चरित (कविता)",
          "जहाँ पहिया है",
          "अकबरी लोटा",
          "सूरदास के पद (कविता)",
          "पानी की कहानी",
          "बाज और साँप (कहानी)",
          "टोपी (कहानी)",
        ],
      },
    ],
    "Social Science": [
      {
        bookName: "Our Past – III (History)",
        publisher: "NCERT",
        chapters: [
          "How, When and Where",
          "From Trade to Territory: The Company Establishes Power",
          "Ruling the Countryside",
          "Tribals, Dikus and the Vision of a Golden Age",
          "When People Rebel 1857 and After",
          "Weavers, Iron Smelters and Factory Owners",
          "Civilising the 'Native', Educating the Nation",
          "Women, Caste and Reform",
          "The Making of the National Movement: 1870s-1947",
          "India After Independence",
        ],
      },
      {
        bookName: "Resources and Development (Geography)",
        publisher: "NCERT",
        chapters: [
          "Resources",
          "Land, Soil, Water, Natural Vegetation and Wildlife Resources",
          "Mineral and Power Resources",
          "Agriculture",
          "Industries",
          "Human Resources",
        ],
      },
      {
        bookName: "Social and Political Life – III (Civics)",
        publisher: "NCERT",
        chapters: [
          "The Indian Constitution",
          "Understanding Secularism",
          "Why Do We Need a Parliament?",
          "Understanding Laws",
          "Judiciary",
          "Understanding Our Criminal Justice System",
          "Understanding Marginalisation",
          "Confronting Marginalisation",
          "Public Facilities",
          "Law and Social Justice",
        ],
      },
    ],
    "Sanskrit": [
      {
        bookName: "Ruchira (Part 3)",
        publisher: "NCERT",
        chapters: [
          "सुभाषितानि",
          "बिलस्य वाणी न कदापि मे श्रुता",
          "डिजीभारतम्",
          "सदैव पुरतो निधेहि चरणम्",
          "कण्टकेनैव कण्टकम्",
          "गृहं शून्यं सुतां विना",
          "भारतजनताऽहम्",
          "संसारसागरस्य नायकाः",
          "सप्तभगिन्यः",
          "नीतिनवनीतम्",
          "सावित्री बाई फुले",
          "कः रक्षति कः रक्षितः",
          "क्षितौ राजते भारतस्वर्णभूमिः",
          "आर्यभटः",
          "प्रहेलिकाः",
        ],
      },
    ],
  },
  "Grade 9": {
    "Mathematics": [
      {
        bookName: "Mathematics (Class IX)",
        publisher: "NCERT",
        chapters: [
          "Number Systems",
          "Polynomials",
          "Coordinate Geometry",
          "Linear Equations in Two Variables",
          "Introduction to Euclid's Geometry",
          "Lines and Angles",
          "Triangles",
          "Quadrilaterals",
          "Areas of Parallelograms and Triangles",
          "Circles",
          "Constructions",
          "Heron's Formula",
          "Surface Areas and Volumes",
          "Statistics",
          "Probability",
        ],
      },
    ],
    "Science": [
      {
        bookName: "Science (Class IX)",
        publisher: "NCERT",
        chapters: [
          "Matter in Our Surroundings",
          "Is Matter Around Us Pure?",
          "Atoms and Molecules",
          "Structure of the Atom",
          "The Fundamental Unit of Life",
          "Tissues",
          "Diversity in Living Organisms",
          "Motion",
          "Force and Laws of Motion",
          "Gravitation",
          "Work and Energy",
          "Sound",
          "Why Do We Fall Ill?",
          "Natural Resources",
          "Improvement in Food Resources",
        ],
      },
    ],
    "English": [
      {
        bookName: "Beehive",
        publisher: "NCERT",
        chapters: [
          "The Fun They Had",
          "The Sound of Music",
          "The Little Girl",
          "A Truly Beautiful Mind",
          "The Snake and the Mirror",
          "My Childhood",
          "Reach for the Top",
          "Kathmandu",
          "If I Were You",
          "The Road Not Taken (Poem)",
          "Wind (Poem)",
          "Rain on the Roof (Poem)",
          "The Lake Isle of Innisfree (Poem)",
          "A Legend of the Northland (Poem)",
          "No Men Are Foreign (Poem)",
          "On Killing a Tree (Poem)",
          "A Slumber Did My Spirit Seal (Poem)",
        ],
      },
      {
        bookName: "Moments",
        publisher: "NCERT (Supplementary)",
        chapters: [
          "The Lost Child",
          "The Adventures of Toto",
          "Iswaran the Storyteller",
          "In the Kingdom of Fools",
          "The Happy Prince",
          "Weathering the Storm in Ersama",
          "The Last Leaf",
          "A House Is Not a Home",
          "The Accidental Tourist",
          "The Beggar",
        ],
      },
    ],
    "Hindi": [
      {
        bookName: "Kshitij (Part 1)",
        publisher: "NCERT",
        chapters: [
          "दो बैलों की कथा – प्रेमचंद",
          "ल्हासा की ओर – राहुल सांकृत्यायन",
          "उपभोक्तावाद की संस्कृति – श्यामाचरण दुबे",
          "साँवले सपनों की याद – जाबिर हुसैन",
          "नाना साहब की पुत्री – चपला देवी",
          "प्रेमचंद के फटे जूते – हरिशंकर परसाई",
          "मेरे बचपन के दिन – महादेवी वर्मा",
          "एक कुत्ता और एक मैना – हजारी प्रसाद द्विवेदी",
          "सखियाँ एवं सबद (कविता) – कबीर",
          "वाख (कविता) – ललद्यद",
          "सवैये (कविता) – रसखान",
          "कैदी और कोकिला (कविता) – माखनलाल चतुर्वेदी",
          "ग्राम श्री (कविता) – सुमित्रानंदन पंत",
          "चंद्र गहना से लौटती बेर (कविता) – केदारनाथ अग्रवाल",
          "मेघ आए (कविता) – सर्वेश्वर दयाल सक्सेना",
          "यमराज की दिशा (कविता) – चंद्रकांत देवताले",
          "बच्चे काम पर जा रहे हैं (कविता) – राजेश जोशी",
        ],
      },
    ],
    "Social Science": [
      {
        bookName: "India and the Contemporary World – I (History)",
        publisher: "NCERT",
        chapters: [
          "The French Revolution",
          "Socialism in Europe and the Russian Revolution",
          "Nazism and the Rise of Hitler",
          "Forest Society and Colonialism",
          "Pastoralists in the Modern World",
        ],
      },
      {
        bookName: "Contemporary India – I (Geography)",
        publisher: "NCERT",
        chapters: [
          "India – Size and Location",
          "Physical Features of India",
          "Drainage",
          "Climate",
          "Natural Vegetation and Wildlife",
          "Population",
        ],
      },
      {
        bookName: "Democratic Politics – I (Civics)",
        publisher: "NCERT",
        chapters: [
          "What is Democracy? Why Democracy?",
          "Constitutional Design",
          "Electoral Politics",
          "Working of Institutions",
          "Democratic Rights",
        ],
      },
      {
        bookName: "Economics (Class IX)",
        publisher: "NCERT",
        chapters: [
          "The Story of Village Palampur",
          "People as Resource",
          "Poverty as a Challenge",
          "Food Security in India",
        ],
      },
    ],
    "Sanskrit": [
      {
        bookName: "Shemushi (Part 1)",
        publisher: "NCERT",
        chapters: [
          "भारतीवसन्तगीतिः",
          "स्वर्णकाकः",
          "गोदोहनम्",
          "कल्पतरूः",
          "सूक्तिमौक्तिकम्",
          "भ्रान्तो बालः",
          "प्रत्यभिज्ञानम्",
          "लौहतुला",
          "सिकतासेतुः",
          "जटायोः शौर्यम्",
          "पर्यावरणम्",
          "वाड्मनःप्राणस्वरूपम्",
        ],
      },
    ],
  },
  "Grade 10": {
    "Mathematics": [
      {
        bookName: "Mathematics (Class X)",
        publisher: "NCERT",
        chapters: [
          "Real Numbers",
          "Polynomials",
          "Pair of Linear Equations in Two Variables",
          "Quadratic Equations",
          "Arithmetic Progressions",
          "Triangles",
          "Coordinate Geometry",
          "Introduction to Trigonometry",
          "Some Applications of Trigonometry",
          "Circles",
          "Constructions",
          "Areas Related to Circles",
          "Surface Areas and Volumes",
          "Statistics",
          "Probability",
        ],
      },
    ],
    "Science": [
      {
        bookName: "Science (Class X)",
        publisher: "NCERT",
        chapters: [
          "Chemical Reactions and Equations",
          "Acids, Bases and Salts",
          "Metals and Non-metals",
          "Carbon and its Compounds",
          "Periodic Classification of Elements",
          "Life Processes",
          "Control and Coordination",
          "How do Organisms Reproduce?",
          "Heredity and Evolution",
          "Light – Reflection and Refraction",
          "Human Eye and Colourful World",
          "Electricity",
          "Magnetic Effects of Electric Current",
          "Sources of Energy",
          "Our Environment",
          "Management of Natural Resources",
        ],
      },
    ],
    "English": [
      {
        bookName: "First Flight",
        publisher: "NCERT",
        chapters: [
          "A Letter to God",
          "Nelson Mandela: Long Walk to Freedom",
          "Two Stories About Flying",
          "From the Diary of Anne Frank",
          "Glimpses of India",
          "Mijbil the Otter",
          "Madam Rides the Bus",
          "The Sermon at Benares",
          "The Proposal",
          "Dust of Snow (Poem)",
          "Fire and Ice (Poem)",
          "A Tiger in the Zoo (Poem)",
          "How to Tell Wild Animals (Poem)",
          "The Ball Poem (Poem)",
          "Amanda! (Poem)",
          "The Trees (Poem)",
          "Fog (Poem)",
          "The Tale of Custard the Dragon (Poem)",
          "For Anne Gregory (Poem)",
        ],
      },
      {
        bookName: "Footprints without Feet",
        publisher: "NCERT (Supplementary)",
        chapters: [
          "A Triumph of Surgery",
          "The Thief's Story",
          "The Midnight Visitor",
          "A Question of Trust",
          "Footprints without Feet",
          "The Making of a Scientist",
          "The Necklace",
          "The Hack Driver",
          "Bholi",
          "The Book That Saved the Earth",
        ],
      },
    ],
    "Hindi": [
      {
        bookName: "Kshitij (Part 2)",
        publisher: "NCERT",
        chapters: [
          "सूरदास – पद",
          "तुलसीदास – राम-लक्ष्मण-परशुराम संवाद",
          "देव – सवैया और कवित्त",
          "जयशंकर प्रसाद – आत्मकथ्य",
          "सूर्यकान्त त्रिपाठी 'निराला' – उत्साह और अट नहीं रही",
          "नागार्जुन – यह दंतुरित मुसकान और फसल",
          "गिरिजा कुमार माथुर – छाया मत छूना",
          "ऋतुराज – कन्यादान",
          "मंगलेश डबराल – संगतकार",
          "स्वयं प्रकाश – नेताजी का चश्मा",
          "रामवृक्ष बेनीपुरी – बालगोबिन भगत",
          "यशपाल – लखनवी अंदाज़",
          "सर्वेश्वर दयाल सक्सेना – एक कहानी यह भी",
          "मन्नू भंडारी – एक कहानी यह भी",
          "महावीर प्रसाद द्विवेदी – स्त्री शिक्षा के विरोध कुतर्कों का खंडन",
          "यतीन्द्र मिश्र – नौबतखाने में इबादत",
          "भदंत आनंद कौसल्यायन – संस्कृति",
        ],
      },
    ],
    "Social Science": [
      {
        bookName: "India and the Contemporary World – II (History)",
        publisher: "NCERT",
        chapters: [
          "The Rise of Nationalism in Europe",
          "Nationalism in India",
          "The Making of a Global World",
          "The Age of Industrialisation",
          "Print Culture and the Modern World",
        ],
      },
      {
        bookName: "Contemporary India – II (Geography)",
        publisher: "NCERT",
        chapters: [
          "Resources and Development",
          "Forest and Wildlife Resources",
          "Water Resources",
          "Agriculture",
          "Minerals and Energy Resources",
          "Manufacturing Industries",
          "Lifelines of National Economy",
        ],
      },
      {
        bookName: "Democratic Politics – II (Civics)",
        publisher: "NCERT",
        chapters: [
          "Power Sharing",
          "Federalism",
          "Democracy and Diversity",
          "Gender, Religion and Caste",
          "Popular Struggles and Movements",
          "Political Parties",
          "Outcomes of Democracy",
          "Challenges to Democracy",
        ],
      },
      {
        bookName: "Understanding Economic Development",
        publisher: "NCERT",
        chapters: [
          "Development",
          "Sectors of the Indian Economy",
          "Money and Credit",
          "Globalisation and the Indian Economy",
          "Consumer Rights",
        ],
      },
    ],
    "Sanskrit": [
      {
        bookName: "Shemushi (Part 2)",
        publisher: "NCERT",
        chapters: [
          "शुचिपर्यावरणम्",
          "बुद्धिर्बलवती सदा",
          "व्यायामः सर्वदा पथ्यः",
          "शिशुलालनम्",
          "जननी तुल्यवत्सला",
          "सुभाषितानि",
          "सौहार्दं प्रकृतेः शोभा",
          "विचित्रः साक्षी",
          "सूक्तयः",
          "अनयोक्त्यः",
          "प्राणेभ्योऽपि प्रियः सुह्रद्",
          "अन्योक्तयः",
        ],
      },
    ],
  },
};

export function getSubjectBooks(className: string, subject: string): BookInfo[] {
  const gradeData = NCERT_CHAPTER_DATA[className];
  if (!gradeData) return [];

  const subjectLower = subject.toLowerCase().trim();

  for (const [key, books] of Object.entries(gradeData)) {
    if (key.toLowerCase() === subjectLower) return books;
    if (subjectLower.includes(key.toLowerCase()) || key.toLowerCase().includes(subjectLower)) return books;
  }

  if (subjectLower.includes("math")) return gradeData["Mathematics"] || [];
  if (subjectLower.includes("sci") || subjectLower.includes("physics") || subjectLower.includes("chemistry") || subjectLower.includes("biology")) return gradeData["Science"] || [];
  if (subjectLower.includes("eng")) return gradeData["English"] || [];
  if (subjectLower.includes("hindi")) return gradeData["Hindi"] || [];
  if (subjectLower.includes("social") || subjectLower.includes("history") || subjectLower.includes("geography") || subjectLower.includes("civics") || subjectLower.includes("economics")) return gradeData["Social Science"] || [];
  if (subjectLower.includes("sanskrit")) return gradeData["Sanskrit"] || [];
  if (subjectLower.includes("evs") || subjectLower.includes("environmental")) return gradeData["EVS"] || [];

  return [];
}

export function getChaptersForBook(className: string, subject: string, bookName: string): string[] {
  const books = getSubjectBooks(className, subject);
  const book = books.find(b => b.bookName === bookName);
  return book ? book.chapters : [];
}

export function getAvailableSubjects(className: string): string[] {
  const gradeData = NCERT_CHAPTER_DATA[className];
  if (!gradeData) return [];
  return Object.keys(gradeData);
}
