import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import logoImage from "@assets/IMG_6540_(1)_1772323458180.png";
import { ThemeToggle } from "@/components/ThemeToggle";

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="sticky top-0 z-50 bg-white/80 dark:bg-gray-900/80 backdrop-blur-lg border-b border-border/50">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <img src={logoImage} alt="Qik Worksheet" className="w-20 h-20 rounded-lg object-contain drop-shadow-md logo-vibrant" />
            <span className="text-lg font-display font-bold text-gradient-primary">Qik Worksheets</span>
          </Link>
          <ThemeToggle />
        </div>
      </nav>

      <div className="container mx-auto max-w-3xl px-4 py-12">
        <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-8">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>

        <h1 className="text-3xl sm:text-4xl font-display font-bold mb-2" data-testid="heading-terms">Terms and Conditions</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString("en-IN", { month: "long", year: "numeric" })}</p>

        <div className="prose prose-sm dark:prose-invert max-w-none space-y-6 text-foreground/90">
          <p>
            Welcome to Qik Worksheets. By accessing or using our website and services, you agree to be bound by these Terms and Conditions. Please read them carefully before using our platform.
          </p>

          <h2 className="text-xl font-display font-bold mt-8">1. Acceptance of Terms</h2>
          <p>
            By registering for an account, accessing, or using Qik Worksheets, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree, please do not use our services.
          </p>

          <h2 className="text-xl font-display font-bold mt-8">2. Description of Service</h2>
          <p>
            Qik Worksheets is an AI-powered educational worksheet generator that creates curriculum-aligned practice materials for students from Nursery to Grade 10. The service includes worksheet generation, test paper creation, PDF downloads, and child profile management.
          </p>

          <h2 className="text-xl font-display font-bold mt-8">3. User Accounts</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>You must provide accurate and complete information during registration.</li>
            <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
            <li>You must be at least 18 years of age or have parental consent to create an account.</li>
            <li>One person may maintain only one account. Duplicate accounts may be terminated.</li>
          </ul>

          <h2 className="text-xl font-display font-bold mt-8">4. Subscription Plans and Payments</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>Free plan users receive a limited number of worksheets.</li>
            <li>Paid subscriptions are billed as per the selected plan (monthly or annual).</li>
            <li>All payments are processed securely through Razorpay.</li>
            <li>Prices are listed in Indian Rupees (INR) and are inclusive of applicable taxes unless stated otherwise.</li>
            <li>Subscriptions do not auto-renew. You must manually renew when your plan expires.</li>
          </ul>

          <h2 className="text-xl font-display font-bold mt-8">5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Use the service for any unlawful purpose or in violation of any applicable laws.</li>
            <li>Reproduce, distribute, or sell generated worksheets for commercial purposes without authorization.</li>
            <li>Attempt to reverse-engineer, hack, or disrupt the service.</li>
            <li>Share your account credentials with others or allow unauthorized access.</li>
            <li>Use automated scripts or bots to generate worksheets in bulk.</li>
          </ul>

          <h2 className="text-xl font-display font-bold mt-8">6. Intellectual Property</h2>
          <p>
            The Qik Worksheets brand, logo, design, and underlying technology are the intellectual property of Qik Worksheets. Worksheets generated by users are for personal and educational use. The AI-generated content is provided as-is and should be reviewed by educators before use.
          </p>

          <h2 className="text-xl font-display font-bold mt-8">7. Content Accuracy</h2>
          <p>
            While we strive to ensure all AI-generated content is accurate and syllabus-aligned, we do not guarantee 100% accuracy. Teachers and parents are encouraged to review worksheets before distributing them to students. Qik Worksheets is not liable for any errors in generated content.
          </p>

          <h2 className="text-xl font-display font-bold mt-8">8. Limitation of Liability</h2>
          <p>
            Qik Worksheets shall not be liable for any indirect, incidental, special, or consequential damages arising from the use or inability to use our services. Our total liability shall not exceed the amount paid by you for the service in the preceding 12 months.
          </p>

          <h2 className="text-xl font-display font-bold mt-8">9. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your account at any time for violation of these terms. You may also delete your account at any time. Upon termination, your right to use the service ceases immediately.
          </p>

          <h2 className="text-xl font-display font-bold mt-8">10. Changes to Terms</h2>
          <p>
            We may update these Terms and Conditions from time to time. We will notify users of significant changes via email or in-app notification. Continued use of the service after changes constitutes acceptance of the new terms.
          </p>

          <h2 className="text-xl font-display font-bold mt-8">11. Governing Law</h2>
          <p>
            These Terms and Conditions are governed by and construed in accordance with the laws of India. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts in India.
          </p>

          <h2 className="text-xl font-display font-bold mt-8">12. Contact</h2>
          <p>
            For any questions about these Terms and Conditions, please contact us at <a href="mailto:support@qikworksheets.com" className="text-primary hover:underline">support@qikworksheets.com</a>.
          </p>
        </div>
      </div>
    </div>
  );
}
