import { jsPDF } from "jspdf";
import { getAnswerKeyUrl } from "@shared/answerKeyUrl";
import type { Worksheet } from "@shared/schema";

type MatchPair = {
  left: string;
  right: string;
};

type ContentQuestion = {
  question: string;
  options?: string[];
  answerSpaceLines?: number;
  matchPairs?: MatchPair[];
  answer?: string;
};

type ContentSection = {
  type: string;
  title: string;
  questions: ContentQuestion[];
};

type AnswerKeyEntry = {
  sectionIndex: number;
  questionIndex: number;
  answer: string;
};

type WorksheetContent = {
  title?: string;
  instructions?: string;
  sections?: ContentSection[];
  answerKey?: AnswerKeyEntry[];
};

function safeText(value: unknown): string {
  let text = String(value ?? "");

  return text
    .replace(/&amp;/g, "&")
    .replace(/&nbsp;/g, " ")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014\u2212]/g, "-")
    .replace(/×/g, "*")
    .replace(/÷/g, "/")
    .replace(/√/g, "sqrt")
    .replace(/π/g, "pi")
    .replace(/[\u{1F000}-\u{1FAFF}]/gu, "")
    .replace(/[\u2600-\u27BF]/g, "")
    .replace(/[^\x20-\x7E\n\r\t]/g, " ")
    .replace(/[ \t]+/g, " ")
    .trim();
}

export async function generateWhatsAppWorksheetPdf(
  worksheet: Worksheet,
): Promise<Buffer> {
  const doc = new jsPDF({
    unit: "pt",
    format: "letter",
  });

  const PAGE_W = 612;
  const PAGE_H = 792;
  const MARGIN = 36;
  const CONTENT_W = PAGE_W - MARGIN * 2;
  const CONTENT_BOTTOM = PAGE_H - MARGIN;

  let y = MARGIN;
  let pageNumber = 1;

  const content = (worksheet.content || {}) as WorksheetContent;

  /*
   * Generate the same Answer Key QR concept used by the
   * original worksheet.
   *
   * Production:
   * PUBLIC_BASE_URL=https://qikworksheet.in
   *
   * The QR will point to:
   * https://qikworksheet.in/api/answer-key/{worksheetId}
   */
  let qrDataUrl: string | null = null;

  try {
    const QR = await import("qrcode");

    const origin =
      process.env.PUBLIC_BASE_URL ||
      `http://localhost:${process.env.PORT || 5000}`;

    const answerKeyUrl = getAnswerKeyUrl(
      worksheet.id,
      origin,
    );

    console.log("[WhatsApp Worksheet] QR payload:", {
      worksheetId: worksheet.id,
      answerKeyUrl,
    });

    qrDataUrl = await QR.toDataURL(answerKeyUrl, {
      width: 200,
      margin: 1,
      color: {
        dark: "#1a1a2e",
        light: "#ffffff",
      },
    });
  } catch (error) {
    console.warn(
      "[WhatsApp Worksheet] Could not generate QR code:",
      error,
    );
  }

  function addPage() {
    doc.addPage();
    pageNumber++;
    y = MARGIN;
  }

  function ensureSpace(height: number) {
    if (y + height > CONTENT_BOTTOM) {
      addPage();
    }
  }

  function drawHeader() {
    const QR_SIZE = 72;
    const QR_X = PAGE_W - MARGIN - QR_SIZE;
    const QR_Y = MARGIN - 28;
    const TEXT_MAX_W = CONTENT_W - QR_SIZE - 16;

    /*
     * QR code
     */
    if (qrDataUrl) {
      doc.addImage(
  qrDataUrl,
  "PNG",
  QR_X,
  QR_Y,
  QR_SIZE,
  QR_SIZE,
);
    

      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(80, 80, 80);

      doc.text(
        "Scan for Answer Key",
        QR_X + QR_SIZE / 2,
        QR_Y + QR_SIZE + 10,
        { align: "center" },
      );
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);

    const title =
      content.title ||
      `${worksheet.className} - ${worksheet.subject}`;

    const titleLines = doc.splitTextToSize(
      safeText(title),
      TEXT_MAX_W,
    );

    doc.text(titleLines, MARGIN, y);

    y += titleLines.length * 18 + 4;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);

    const meta = [
      worksheet.className,
      worksheet.subject,
      worksheet.topic,
    ]
      .filter(Boolean)
      .join(" | ");

    const metaLines = doc.splitTextToSize(
      safeText(meta),
      TEXT_MAX_W,
    );

    doc.text(metaLines, MARGIN, y);

    y += metaLines.length * 12 + 3;

    if (worksheet.serialNumber) {
      doc.text(
        safeText(`Ref: ${worksheet.serialNumber}`),
        MARGIN,
        y,
      );

      y += 14;
    }

    doc.text(
      safeText(`${worksheet.board} | ${worksheet.difficulty}`),
      MARGIN,
      y,
    );

    y += 8;

    doc.setDrawColor(0);
    doc.setLineWidth(1);

    doc.line(
      MARGIN,
      y,
      PAGE_W - MARGIN,
      y,
    );

    y += 16;
  }

  function drawFooter() {
    const savedY = y;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);

    doc.text(
      "Generated by Qik Worksheet",
      MARGIN,
      PAGE_H - 20,
    );

    doc.text(
      `Page ${pageNumber}`,
      PAGE_W - MARGIN,
      PAGE_H - 20,
      { align: "right" },
    );

    y = savedY;
  }

  function drawInstructions() {
    if (!content.instructions) return;

    const lines = doc.splitTextToSize(
      safeText(content.instructions),
      CONTENT_W - 16,
    );

    const boxHeight =
      lines.length * 13 + 28;

    ensureSpace(boxHeight);

    doc.setFillColor(245, 245, 245);
    doc.setDrawColor(210, 210, 210);

    doc.roundedRect(
      MARGIN,
      y,
      CONTENT_W,
      boxHeight,
      5,
      5,
      "FD",
    );

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);

    doc.text(
      "INSTRUCTIONS",
      MARGIN + 8,
      y + 14,
    );

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);

    doc.text(
      lines,
      MARGIN + 8,
      y + 27,
    );

    y += boxHeight + 14;
  }

  function drawSectionHeader(title: string) {
    ensureSpace(32);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(0, 102, 255);

    doc.text(
      safeText(title),
      MARGIN,
      y,
    );

    y += 6;

    doc.setDrawColor(0, 102, 255);
    doc.setLineWidth(0.7);

    doc.line(
      MARGIN,
      y,
      PAGE_W - MARGIN,
      y,
    );

    y += 14;

    doc.setTextColor(0, 0, 0);
  }

  function drawAnswerLines(count: number) {
    const lineCount = Math.max(
      0,
      Math.min(count, 8),
    );

    if (lineCount === 0) return;

    const required =
      lineCount * 16 + 4;

    ensureSpace(required);

    doc.setDrawColor(210, 210, 210);
    doc.setLineWidth(0.5);

    for (let i = 0; i < lineCount; i++) {
      doc.line(
        MARGIN + 18,
        y + i * 16,
        PAGE_W - MARGIN,
        y + i * 16,
      );
    }

    y += required;
  }

  function drawMcqOptions(options: string[]) {
    if (!options.length) return;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);

    for (let i = 0; i < options.length; i++) {
      const label =
        String.fromCharCode(97 + i);

      const text = safeText(
        `${label}) ${options[i]}`,
      );

      const lines = doc.splitTextToSize(
        text,
        CONTENT_W - 35,
      );

      ensureSpace(
        lines.length * 12 + 2,
      );

      doc.text(
        lines,
        MARGIN + 22,
        y,
      );

      y += lines.length * 12;
    }

    y += 3;
  }

  function drawMatchQuestion(
    question: ContentQuestion,
    number: number,
  ) {
    const pairs =
      question.matchPairs || [];

    const questionLines =
      doc.splitTextToSize(
        safeText(
          `${number}. ${question.question}`,
        ),
        CONTENT_W,
      );

    ensureSpace(
      questionLines.length * 13 + 40,
    );

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);

    doc.text(
      questionLines,
      MARGIN,
      y,
    );

    y +=
      questionLines.length * 13 +
      5;

    if (pairs.length === 0) return;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);

    doc.text(
      "Column A",
      MARGIN + 10,
      y,
    );

    doc.text(
      "Column B",
      MARGIN + 290,
      y,
    );

    y += 12;

    doc.setFont("helvetica", "normal");

    for (let i = 0; i < pairs.length; i++) {
      const left = safeText(
        `${i + 1}. ${pairs[i]?.left}`,
      );

      const right = safeText(
        `${String.fromCharCode(97 + i)}. ${pairs[i]?.right}`,
      );

      const leftLines =
        doc.splitTextToSize(
          left,
          230,
        );

      const rightLines =
        doc.splitTextToSize(
          right,
          230,
        );

      const rowHeight =
        Math.max(
          leftLines.length,
          rightLines.length,
        ) *
          12 +
        4;

      ensureSpace(rowHeight);

      doc.text(
        leftLines,
        MARGIN + 10,
        y,
      );

      doc.text(
        rightLines,
        MARGIN + 290,
        y,
      );

      y += rowHeight;
    }

    y += 8;
  }

  function drawQuestion(
    question: ContentQuestion,
    number: number,
    sectionType: string,
  ) {
    if (sectionType === "match") {
      drawMatchQuestion(
        question,
        number,
      );
      return;
    }

    const questionText =
      safeText(
        `${number}. ${question.question}`,
      );

    const lines =
      doc.splitTextToSize(
        questionText,
        CONTENT_W,
      );

    const answerLines =
      sectionType === "short_answer"
        ? Math.min(
            question.answerSpaceLines ?? 2,
            4,
          )
        : sectionType === "long_answer"
          ? Math.min(
              question.answerSpaceLines ?? 4,
              8,
            )
          : Math.min(
              question.answerSpaceLines ?? 0,
              8,
            );

    ensureSpace(
      lines.length * 13 +
        (question.options?.length || 0) *
          12 +
        answerLines * 16 +
        12,
    );

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);

    doc.text(
      lines,
      MARGIN,
      y,
    );

    y += lines.length * 13;

    if (
      sectionType === "mcq" &&
      question.options
    ) {
      drawMcqOptions(
        question.options,
      );
    }

    if (sectionType !== "mcq") {
      drawAnswerLines(answerLines);
    }

    y += 7;
  }

  /*
   * Draw Answer Key
   */
  function drawAnswerKey() {
    const sections = Array.isArray(
      content.sections,
    )
      ? content.sections
      : [];

    const answerKey = Array.isArray(
      content.answerKey,
    )
      ? content.answerKey
      : [];

    const hasInlineAnswers =
      sections.some((section) =>
        Array.isArray(section.questions)
          ? section.questions.some(
              (question) =>
                Boolean(question.answer),
            )
          : false,
      );

    if (
      answerKey.length === 0 &&
      !hasInlineAnswers
    ) {
      console.warn(
        `[WhatsApp Worksheet] No answer key found for worksheet ${worksheet.id}`,
      );

      return;
    }

    /*
     * Start Answer Key on a fresh page.
     * This keeps the student worksheet separate
     * from the answers.
     */
    doc.addPage();
    pageNumber++;
    y = MARGIN;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);

    doc.text(
      "ANSWER KEY",
      MARGIN,
      y,
    );

    y += 10;

    doc.setDrawColor(0, 102, 255);
    doc.setLineWidth(1);

    doc.line(
      MARGIN,
      y,
      PAGE_W - MARGIN,
      y,
    );

    y += 18;

    for (
      let sectionIndex = 0;
      sectionIndex < sections.length;
      sectionIndex++
    ) {
      const section =
        sections[sectionIndex];

      const questions =
        Array.isArray(
          section.questions,
        )
          ? section.questions
          : [];

      if (questions.length === 0) {
        continue;
      }

      ensureSpace(30);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(0, 102, 255);

      doc.text(
        safeText(
          section.title ||
            `Part ${String.fromCharCode(
              65 + sectionIndex,
            )}`,
        ),
        MARGIN,
        y,
      );

      y += 17;

      for (
        let questionIndex = 0;
        questionIndex < questions.length;
        questionIndex++
      ) {
        const question =
          questions[questionIndex];

        /*
         * Same priority as the original AnswerSheet:
         *
         * 1. content.answerKey
         * 2. question.answer
         */
        const answerFromKey =
          answerKey.find(
            (entry) =>
              entry.sectionIndex ===
                sectionIndex &&
              entry.questionIndex ===
                questionIndex,
          );

        const answer =
          answerFromKey?.answer ||
          question.answer ||
          "";

        if (!answer) {
          continue;
        }

        const answerText =
          safeText(answer);

        const lines =
          doc.splitTextToSize(
            `${questionIndex + 1}. ${answerText}`,
            CONTENT_W,
          );

        ensureSpace(
          lines.length * 13 + 6,
        );

        doc.setFont(
          "helvetica",
          "normal",
        );
        doc.setFontSize(9);
        doc.setTextColor(0, 0, 0);

        doc.text(
          lines,
          MARGIN,
          y,
        );

        y +=
          lines.length * 13 + 6;
      }

      y += 5;
    }
  }

  /*
   * Main worksheet
   */
  drawHeader();

  drawInstructions();

  const sections = Array.isArray(
    content.sections,
  )
    ? content.sections
    : [];

  for (
    let sectionIndex = 0;
    sectionIndex < sections.length;
    sectionIndex++
  ) {
    const section =
      sections[sectionIndex];

    drawSectionHeader(
      section.title ||
        `Part ${String.fromCharCode(
          65 + sectionIndex,
        )}`,
    );

    const questions =
      Array.isArray(
        section.questions,
      )
        ? section.questions
        : [];

    for (
      let questionIndex = 0;
      questionIndex < questions.length;
      questionIndex++
    ) {
      drawQuestion(
        questions[questionIndex],
        questionIndex + 1,
        section.type,
      );
    }

    y += 5;
  }

  /*
   * Answer Key
   */
  drawAnswerKey();

  /*
   * Footer is drawn after all content.
   * It saves/restores y so it never affects pagination.
   */
  const totalPages =
    doc.getNumberOfPages();

  for (
    let i = 1;
    i <= totalPages;
    i++
  ) {
    doc.setPage(i);
    pageNumber = i;
    drawFooter();
  }

  const arrayBuffer =
    doc.output("arraybuffer");

  return Buffer.from(arrayBuffer);
}