/** Shared AI accuracy notice shown under generate actions. */
export function AiAccuracyDisclaimer() {
  return (
    <div className="mt-3 text-xs text-muted-foreground leading-relaxed">
      <strong>Disclaimer:</strong> This worksheet is generated by AI based on your uploaded
      content. While we strive for accuracy, AI can occasionally produce errors or
      &quot;hallucinations.&quot; Please review all questions and answers for educational accuracy
      before distributing them to students.
    </div>
  );
}
